Repository kyma-project/eventing-tools, pull requests merged in 2023-08, with the labels that each got.

#24 add github actions
  .github/workflows/build.yml
  .github/workflows/lint.yml
  .github/workflows/quality.yml
Labels: area/ci, size/L, lgtm

#25 Create dependabot.yml
  .github/dependabot.yml
Labels: area/ci, size/S, lgtm

#32 add required .md files
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  LICENSE
  NOTICE.md
  README.md
Labels: size/L, lgtm

#39 reuse compliance
  .reuse/dep5
  LICENSES/Apache-2.0.txt
  README.md
Labels: size/L, lgtm
