Repository kyma-project/eventing-tools, pull requests merged in 2024-02, with the labels that each got.

#65 Lint Fix: - funlen - thelper - perfsprint - godox - goconst
  README.md
  config/lint/.golangci.yaml
Labels: kind/cleanup, size/M, lgtm, area/cli, cla: yes

#66 rename the cr file in the workflow
  .github/workflows/create-draft-release-reusable.yml
  .github/workflows/render-and-upload-manifests-reusable.yml
  hack/scripts/create_changelog.sh
  hack/scripts/get-version-from-branch.sh
Labels: area/ci, size/L, lgtm, cla: yes

#67 use a commit sha for script instead of main
  .github/workflows/create-draft-release-reusable.yml
Labels: area/ci, size/XS, lgtm, cla: yes

#68 replace action to install yq with some shell commands
  .github/workflows/bump-sec-scanners-config-reusable.yml
Labels: area/ci, size/S, lgtm, cla: yes

#69 get branch-name from github var
  .github/workflows/trigger-prow-build-job-reusable.yml
Labels: area/ci, size/XS, lgtm, cla: yes

#70 pass-commit-ref-as-input
  .github/workflows/trigger-prow-build-job-reusable.yml
Labels: area/ci, size/XS, lgtm, cla: yes

#71 remove secrets from trigger-prow-build-job-reusable
  .github/workflows/trigger-prow-build-job-reusable.yml
Labels: area/ci, size/S, lgtm, cla: yes

#72 fetch all history in the workflow create-draft-release-reusable
  .github/workflows/create-draft-release-reusable.yml
Labels: area/ci, size/XS, lgtm, cla: yes

#74 Add imports used by the eventing-auth-manager repository
  config/lint/.golangci.yaml
Labels: size/M, lgtm, cla: yes

#77 feat: add rules for PRs
  .github/dependabot.yml
  .github/workflows/lint-conventional-prs.yml
  internal/loadtest/sender/legacyevent/sender.go
Labels: area/ci, size/M, lgtm, cla: yes

#85 chore: change dependabot config to weekly schedule
  .github/dependabot.yml
Labels: area/ci, size/S, lgtm, cla: yes

#90 fix: schedule of dependabot
  .github/dependabot.yml
Labels: area/ci, size/XS, lgtm, cla: yes

#92 chore: linter settings for nats-manager
  config/lint/.golangci.yaml
Labels: area/ci, size/M, lgtm, cla: yes
