Repository kyma-project/eventing-tools, pull requests merged in 2024-01, with the labels that each got.

#53 add script to get version number from a git branch
  hack/scripts/get-version-from-branch.sh
Labels: size/M, lgtm, cla: yes

#54 add a reusable unit test github action workflow
  .github/workflows/unit-test-reusable.yml
Labels: area/ci, size/S, lgtm, cla: yes

#55 add a reusable linting github action workflow
  .github/workflows/lint-reusable.yml
Labels: area/ci, size/S, lgtm, cla: yes

#56 add bump-sec-scanners-config-reusable.yml
  .github/workflows/bump-sec-scanners-config-reusable.yml
Labels: area/ci, size/L, lgtm, cla: yes

#57 Centralized linter
  .github/workflows/lint-go-reusable.yml
  .github/workflows/lint-reusable.yml
  config/lint/.golangci.yaml
Labels: area/ci, size/L, lgtm, cla: yes

#58 Modify Job name
  .github/workflows/lint-go-reusable.yml
  config/lint/.golangci.yaml
Labels: area/ci, size/XS, kind/cleanup, lgtm, cla: yes

#59 Lint Fix: tagalign
  config/lint/.golangci.yaml
Labels: kind/cleanup, lgtm, cla: yes

#60 Lint Fix: gci
  config/lint/.golangci.yaml
Labels: size/XS, lgtm, cla: yes

#61 Lint Fix: gomoddirectives & gofumpt
  config/lint/.golangci.yaml
Labels: size/XS, kind/cleanup, lgtm, area/cli, cla: yes

#62 Prometheus for gomoddirectives white list
  config/lint/.golangci.yaml
Labels: size/XS, lgtm, cla: yes

#64 Lint Fix: goerr113
  config/lint/.golangci.yaml
Labels: kind/feature, size/XS, lgtm, area/cli, cla: yes
